version: "2"

linters:
  default: none
  enable:
    - dupl
    - errcheck
#    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - revive
    - gosec
    - govet
    - ineffassign
#    - lll
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - unused

formatters:
  enable:
    - gofmt
    - goimports
