name: Release
on:
  workflow_dispatch:
    inputs:
      skip_tag:
        description: 'Skip semantic-release (use existing tag)'
        type: boolean
        default: false
  # Release patches and security updates weekly
  schedule:
    - cron: "0 0 * * 1"

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip_tag && github.ref == 'refs/heads/master' }}
    steps:

    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v6
      with:
        node-version: 24

    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install semantic-release
      run: yarn global add --no-progress --non-interactive "semantic-release" "@semantic-release/exec"

    - name: Run semantic-release
      run: $(yarn global bin)/semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: [tag]
    if: always() && (needs.tag.result == 'success' || needs.tag.result == 'skipped')
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24
        id: go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
