name: Test PR
on:
  pull_request_target:
  workflow_dispatch:

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.24
      id: go

    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v9

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.24
      id: go

    - name: Checkout
      uses: actions/checkout@v6
      with:
        ref: "refs/pull/${{ github.event.number }}/merge"

    - name: Test
      run: go test -coverprofile cover.out ./...


  image-scan:
    name: Image Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        ref: "refs/pull/${{ github.event.number }}/merge"

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.24
      id: go

    - name: Build binary
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o php-fpm_exporter .

    - name: Build image
      run: docker build -t php-fpm_exporter:scan .

    - name: Scan image
      uses: anchore/scan-action@v7.4.0
      id: scan
      with:
        image: "php-fpm_exporter:scan"
        acs-report-enable: true
        fail-build: false

    - name: Upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
